---
- name: Configure Java OpenJDK
  template:
    src: ansible_java.sh.j2
    dest: /etc/profile.d/ansible_java.sh
    mode: "0644"
  when: openjdk_java_home | length or openjdk_java_tool_options | length
