---
- name: Install OpenJDK (RedHat)
  yum:
    name: "{{ openjdk_packages[openjdk_version] }}"
  when: ansible_os_family == "RedHat"

- name: Add repository (Ubuntu)
  apt_repository:
    repo: ppa:openjdk-r/ppa
  when: ansible_distribution == "Ubuntu"

- name: Install OpenJDK (Debian)
  apt:
    name: "{{ openjdk_packages[openjdk_version] }}"
    update_cache: true
  when: ansible_os_family == "Debian"
