---
- name: Accept license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Java Oracle
  apt:
    name: "oracle-java{{ java_version }}-installer"
    state: present
    update_cache: yes
